default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development_pg

test:
  <<: *default
  database: db/test_pg

production:
  <<: *default
  database: db/production_pg
